apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aks-helloworld
    version: 1.0.0
  name: aks-helloworld
  namespace: demo-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld
      version: 1.0.0
  template:
    metadata:
      labels:
        app: aks-helloworld
        version: 1.0.0
    spec:
      containers:
        - name: canary-demo
          image: helayoty/canary-demo:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
          env:
            - name: VERSION
              value: "1.0.0"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-svc
  namespace: demo-prod
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    version: 1.0.0
    app: aks-helloworld
