apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aks-helloworld
    version: 1.0.0
  name: aks-helloworld
  namespace: demo-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld
  template:
    metadata:
      labels:
        app: aks-helloworld
    spec:
      containers:
      - name: aks-helloworld
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS)"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld
  namespace: demo-prod
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    version: 1.0.0
    app: aks-helloworld
